# Generated by Django 5.0.1 on 2024-01-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_photo',
            field=models.ImageField(blank=True, null=True, upload_to='posts/posts_photo'),
        ),
    ]
